/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "var(--color-surface-bright)",
        "surface-variant": "var(--color-surface-variant)",
        "error": "var(--color-error)",
        "outline-variant": "var(--color-outline-variant)",
        "primary": "var(--color-primary)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-background": "var(--color-on-background)",
        "background": "var(--color-background)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface": "var(--color-surface)",
        "on-primary": "var(--color-on-primary)",
        "surface-container": "var(--color-surface-container)",
        "outline": "var(--color-outline)",
        "primary-container": "var(--color-primary-container)",
        "on-surface": "var(--color-on-surface)",
        "on-error": "var(--color-on-error)",
        "on-error-container": "var(--color-on-error-container)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "error-container": "var(--color-error-container)",
        // other kept original colors for compatibility if needed
        "tertiary-fixed-dim": "#b4c5ff",
        "on-tertiary": "#082b72",
        "on-primary-fixed-variant": "#574500",
        "primary-fixed-dim": "#e9c349",
        "secondary-fixed-dim": "#c8c6c5",
        "secondary": "#c8c6c5",
        "tertiary-fixed": "#dbe1ff",
        "secondary-fixed": "#e4e2e1",
        "on-primary-fixed": "#241a00",
        "tertiary-container": "#97b0ff",
        "on-secondary-container": "#b7b5b4",
        "inverse-on-surface": "#313030",
        "secondary-container": "#474746",
        "primary-fixed": "#ffe088",
        "on-secondary-fixed-variant": "#474746",
        "on-secondary": "#303030",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-container": "#254188",
        "tertiary": "#bfcdff",
        "on-tertiary-fixed-variant": "#27438a",
        "inverse-primary": "#735c00",
        "on-secondary-fixed": "#1b1c1c",
        "on-tertiary-fixed": "#00174b"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem", 
        "lg": "0.5rem", 
        "xl": "0.75rem", 
        "2xl": "1.5rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
