/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#3a3939",
        "tertiary-fixed-dim": "#b4c5ff",
        "surface-variant": "#353534",
        "on-tertiary": "#082b72",
        "error": "#ffb4ab",
        "outline-variant": "#4d4635",
        "primary": "#f2ca50",
        "on-primary-fixed-variant": "#574500",
        "primary-fixed-dim": "#e9c349",
        "surface-container-lowest": "#0e0e0e",
        "secondary-fixed-dim": "#c8c6c5",
        "secondary": "#c8c6c5",
        "on-background": "#e5e2e1",
        "background": "#131313",
        "tertiary-fixed": "#dbe1ff",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed": "#e4e2e1",
        "on-primary-fixed": "#241a00",
        "on-surface-variant": "#d0c5af",
        "surface": "#131313",
        "tertiary-container": "#97b0ff",
        "on-secondary-container": "#b7b5b4",
        "on-primary": "#3c2f00",
        "surface-container": "#201f1f",
        "outline": "#99907c",
        "inverse-on-surface": "#313030",
        "primary-container": "#d4af37",
        "surface-tint": "#e9c349",
        "secondary-container": "#474746",
        "primary-fixed": "#ffe088",
        "on-surface": "#e5e2e1",
        "surface-dim": "#131313",
        "on-secondary-fixed-variant": "#474746",
        "on-secondary": "#303030",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-container": "#254188",
        "tertiary": "#bfcdff",
        "on-error": "#690005",
        "on-primary-container": "#554300",
        "on-tertiary-fixed-variant": "#27438a",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#353534",
        "surface-container-low": "#1c1b1b",
        "inverse-primary": "#735c00",
        "on-secondary-fixed": "#1b1c1c",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#00174b"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem", 
        "lg": "0.5rem", 
        "xl": "0.75rem", 
        "2xl": "1.5rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
